CREATE  TABLE CAMPUS
(
    CAMPUS_ID       VARCHAR2(5)      NOT NULL,
    CAMPUS_NAME     VARCHAR2(100),
    STREET          VARCHAR2(100),
    CITY            VARCHAR2(100),
    STATE           VARCHAR2(100),
    ZIP             VARCHAR2(100),
    PHONE           VARCHAR2(100),
    CAMPUS_DISCOUNT DECIMAL(2, 2),
    CONSTRAINT  CAMPUS_PK   PRIMARY KEY (Campus_ID)
);

CREATE  TABLE POSITION
(
    POSITION_ID     VARCHAR2(5)         NOT NULL,
    POSITION        VARCHAR2(100),
    YEARLY_MEMBERSHIP_FREE  DECIMAL(7, 2),
    CONSTRAINT  POSITION_PK PRIMARY KEY (POSITION_ID)
);

CREATE  TABLE MEMBERS
(
    MEMBER_ID           VARCHAR2(5)     NOT NULL,
    LAST_NAME           VARCHAR2(100),
    FIRST_NAME          VARCHAR2(100),
    CAMPUS_ADDRESS      VARCHAR2(100),
    CAMPUS_PHONE        VARCHAR2(100),
    CAMPUS_ID           VARCHAR2(5),
    POSITION_ID         VARCHAR2(5),
    CONTRACT_DURATION   INTEGER,
    CONSTRAINT  MEMBERS_PK  PRIMARY KEY (MEMBER_ID)
);
ALTER TABLE MEMBERS ADD CONSTRAINT  FK_MEMBERS  FOREIGN KEY (POSITION_ID) 
    REFERENCES POSITION(POSITION_ID);

CREATE  TABLE PRICES
(
    FOOD_ITEM_TYPE_ID       NUMBER(20)  NOT NULL,
    MEAL_TYPE               VARCHAR2(100),
    MEAL_PRICE              DECIMAL(7,2),
    CONSTRAINT  PRICES_PK PRIMARY KEY (FOOD_ITEM_TYPE_ID)
);

CREATE  TABLE FOOD_ITEMS
(
    FOOD_ITEM_ID        VARCHAR2(5),
    FOOD_ITEM_NAME      VARCHAR2(100),
    FOOD_ITEM_TYPE_ID   NUMBER(20),
    CONSTRAINT  FOOD_ITEMS_PK PRIMARY KEY (FOOD_ITEM_ID)
);
ALTER TABLE FOOD_ITEMS ADD CONSTRAINT  FK_FOOD_ITEMS FOREIGN KEY (FOOD_ITEM_TYPE_ID)
    REFERENCES PRICES(FOOD_ITEM_TYPE_ID);

CREATE  TABLE ORDERS
(
    ORDER_ID    VARCHAR2(5),
    MEMBER_ID   VARCHAR2(5),
    ORDER_DATE  VARCHAR2(25),
    CONSTRAINT  ORDERS_PK   PRIMARY KEY (ORDER_ID)
);
ALTER TABLE ORDERS ADD CONSTRAINT  FK_ORDERS   FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBERS(MEMBER_ID);

CREATE  TABLE ORDER_LINE
(
    ORDER_ID        VARCHAR2(5)     NOT NULL,
    FOOD_ITEM_ID    VARCHAR2(5),
    QUANTITY        INTEGER,
    CONSTRAINT  OL_PK  PRIMARY KEY (FOOD_ITEM_ID, ORDER_ID)
);
ALTER TABLE ORDER_LINE ADD CONSTRAINT FK_OLO FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS(ORDER_ID);
ALTER TABLE ORDER_LINE ADD CONSTRAINT FK_OLF FOREIGN KEY (FOOD_ITEM_ID)
    REFERENCES FOOD_ITEMS(FOOD_ITEM_ID);
